[package]
name = "index"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "*"
byteorder = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
anyhow = "*"

[lints.rust]
unused_variables = "allow"
dead_code = "allow"
